server:
  port: 8085
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true          #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
zuul:
  routes:
    route-action:
      serviceId: eureka-user
      path: /**